id: A93159424
title: A Simple Method of Transference for Helpless Animals
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:12:28.571226
  last_modified_at: 2022-02-28 23:12:28.571233
